spring.application.name=project

# ==================================
# CONFIGURACIÓN DE CONEXIÓN DE BASE DE DATOS (SQL Server)
# ==================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Password123#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==================================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# ddl-auto: update (crea/actualiza las tablas automáticamente al arrancar)
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en consola (ideal para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
